"""Test data builders.

Values are generated per run so repeated executions never collide on the
shared demo backend.
"""
from __future__ import annotations

import random
import string
from dataclasses import dataclass, field


def _suffix(length: int = 8) -> str:
    return "".join(random.choices(string.ascii_lowercase + string.digits, k=length))


@dataclass
class ContactMessage:
    first_name: str = "Test"
    last_name: str = "Engineer"
    email: str = field(default_factory=lambda: f"qa.{_suffix()}@example.com")
    subject: str = "Customer service"
    message: str = (
        "Automated check of the contact form. "
        "This message is generated by a test suite and needs no reply."
    )

    def as_dict(self) -> dict[str, str]:
        return {
            "first_name": self.first_name,
            "last_name": self.last_name,
            "email": self.email,
            "subject": self.subject,
            "message": self.message,
        }


@dataclass
class GuestCustomer:
    first_name: str = "Test"
    last_name: str = "Buyer"
    email: str = field(default_factory=lambda: f"buyer.{_suffix()}@example.com")
    street: str = "Test Street"
    house_number: str = "12"
    city: str = "Podgorica"
    state: str = "Podgorica"
    postal_code: str = "81000"
    country: str = "Montenegro"
